on: [push, pull_request]

name: CI

jobs:
  ci:
    name: CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: check
